server:
  ssl:
    key-store: C:\Users\Пользователь\.keystore\hospital.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: adminbackend 
    key-password: password

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: healer_backend
    password: healer_backend_password
    
  jpa:
    properties:
      hibernate:
        show_sql: true
