spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: healer_backend
    password: healer_backend_password
    
  jpa:
    properties:
      hibernate:
        show_sql: true
